export const GET_RESTAURANT_PHOTOS = 'GET_RESTAURANT_PHOTOS';
export const SET_RESTAURANT_ERROR = 'SET_RESTAURANT_ERROR';
export const CLEAR_RESTAURANT = 'CLEAR_RESTAURANT';
export const SET_ERROR = 'SET_ERROR';

export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const SET_FILTER = 'SET_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const UPDATE_INDEX = 'UPDATE_INDEX';
export const REPORT_PROBLEM_PHOTO = 'REPORT_PROBLEM_PHOTO';
export const SHOW_REPORT_PHOTO = 'SHOW_REPORT_PHOTO';
export const CLOSE_REPORT_PHOTO = 'CLOSE_REPORT_PHOTO';
